rfc: 0012-changelog-specification.md
deepin-community/rfcs pull request #12
Opened 2024-07-25 02:31 UTC by Zeno-sole

2024-07-25 02:35 UTC, Zeno-sole commented
add review @UTsweetyfish  @hudeng-go  @RevySR  @BLumia @MingcongBai @xzl01 @YukariChiba

2024-07-26 00:23 UTC, hudeng-go approved these changes

2024-07-29 01:51 UTC, Zeno-sole commented
todo： 多版本共存时安全更新版本号机制

2024-07-29 02:41 UTC, BLumia commented on rfcs/0012-changelog-specification.md
> +  `x.y.zdeepin0+rb1`
这部分的 GitHub Markdown 渲染效果和预期一致吗？1~4可能也有类似问题。

2024-07-30 08:16 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +  `x.y.zdeepin0+rb1`
已更新

2024-07-30 08:16 UTC, Zeno-sole commented
> todo： 多版本共存时安全更新版本号机制

已补充

2024-07-30 11:12 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> + ver2：表示来自deepin社区的patch数量，依次递增，可为空
ver2不是上次纠正过不可为空了吗

2024-07-30 11:13 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> +因此重新修订native版本规范，形式为 `upstreamversiondeepin${ver2}`
ubuntu这边使用的是upstreamversion+ubuntu${ver2}

2024-07-30 11:15 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> +对于v23版本 `upstreamversion-${ver1}deepin${ver2}+deb23u1` 对于v26版本 `upstreamversion-${ver1}deepin${ver2}+deb26u1` ，对于后续的更新，$num值都应当累加，由于版本号形式较多建议使用 `dpkg --compare-versions` 验证版本号是否符合要求。
对deb23u1有疑问 建议使用dee23u1 不要复用deb表示 避免debian包和deepin包混用

2024-07-31 05:07 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +对于v23版本 `upstreamversion-${ver1}deepin${ver2}+deb23u1` 对于v26版本 `upstreamversion-${ver1}deepin${ver2}+deb26u1` ，对于后续的更新，$num值都应当累加，由于版本号形式较多建议使用 `dpkg --compare-versions` 验证版本号是否符合要求。
dde23u1看起来也不太合适， 不如使用dp23u1(dp为deepin的缩写)

2024-07-31 05:11 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> + ver2：表示来自deepin社区的patch数量，依次递增，可为空
那ver2默认从开始计算？

2024-07-31 08:41 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +因此重新修订native版本规范，形式为 `upstreamversiondeepin${ver2}`
这种形式看起来更好一些，同意+1

2024-08-01 08:35 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> +对于v23版本 `upstreamversion-${ver1}deepin${ver2}+deb23u1` 对于v26版本 `upstreamversion-${ver1}deepin${ver2}+deb26u1` ，对于后续的更新，$num值都应当累加，由于版本号形式较多建议使用 `dpkg --compare-versions` 验证版本号是否符合要求。
> dde23u1看起来也不太合适， 不如使用dp23u1(dp为deepin的缩写)

同意

2024-08-01 08:37 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> +情况1：ver2不为空时直接+rb{ver}后缀，表现形式为`x.y.zdeepin1+rb1`
> 因此重新修订native版本规范，形式为 `upstreamversion+deepin${ver2}`

这里关联版本号也需要处理
但是还有个问题 没有体现这个包是deepin维护还是debian维护

2024-08-05 02:31 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +情况1：ver2不为空时直接+rb{ver}后缀，表现形式为`x.y.zdeepin1+rb1`
有deepin{ver2} 后缀的表示有来自deepin社区的修改

2024-08-08 13:02 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> + ver2：表示来自deepin社区的patch数量，依次递增，不可为空从0开始计算
认为这不应该是patch数量 有可能是调整一次rules 也需要递增的位置
显示数量感觉没什么用处

2024-08-08 13:03 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> +
缺少bootstrap包的构建方式

比如利用~来构造依赖少的bootstrap包的版本号

2024-08-08 13:07 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> + ver2：表示来自deepin社区的patch数量，依次递增，不可为空从0开始计算
那就用修改次数吧 PR为单位

2024-08-09 10:04 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +
中间状态的包不应该推送到集成状态，这种情况应该在开发过程处理掉

2024-08-19 07:48 UTC, BLumia reviewed
总体没有问题，请酌情调整格式。[现有文档的渲染效果](https://github.com/deepin-community/rfcs/blob/d783d84e48ef962f4efbcf7218b267cd62caef30/rfcs/0012-changelog-specification.md)存在一些问题（下面也附带了相对应的修改建议）

2024-08-19 07:48 UTC, BLumia commented on rfcs/0012-changelog-specification.md
> + ver2：表示来自deepin社区的修改，依次递增，不可为空从0开始计算
```suggestion

- ver1：ver1为0时表示 deepin自行打包的上游软件，ver1不为0时表示来自上游的quilt软件包自带的-ver版本
- ver2：表示来自deepin社区的修改，依次递增，不可为空从0开始计算
```

2024-08-19 07:48 UTC, BLumia commented on rfcs/0012-changelog-specification.md
> +对于非上述情况时应当遵循上文的版本号规范提交。
```suggestion
对于相同版本软件包需要在两个以上的版本中做安全更新(例如 v23 and v26)时，为确保版本号正确，必须大于当前软包版本且小于后续发行版中的软件包版本，请示在版本号后缀中添加+dp${version}u${num}形式

对于v23版本 `upstreamversion-${ver1}deepin${ver2}+dp23u1` 对于v26版本 `upstreamversion-${ver1}deepin${ver2}+dp26u1` ，对于后续的更新，$num值都应当累加，由于版本号形式较多建议使用 `dpkg --compare-versions` 验证版本号是否符合要求。

对于非上述情况时应当遵循上文的版本号规范提交。
```

2024-08-19 07:48 UTC, BLumia commented on rfcs/0012-changelog-specification.md
> +native软件包没有-的连字符，因此直接在上游版本号后添加+deepin${ver2} 标记来自deepin的修改
```suggestion

将native软件包直接改成quilt格式存在一些changelog版本格式不兼容问题，
因此重新修订native版本规范，形式为 `upstreamversion+deepin${ver2}`。
native软件包没有-的连字符，因此直接在上游版本号后添加+deepin${ver2} 标记来自deepin的修改。
```

2024-08-19 07:48 UTC, BLumia commented on rfcs/0012-changelog-specification.md
> +
```suggestion

```

2024-08-19 07:55 UTC, kt286 commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
为啥不定一个全局统一的版本号规范呢，这样的话不用判断那么多种情况了
我的建议如下
upstreamversion+deepin${ver1}[+dp26u${ver2}][+u${ver3}][+rb${ver4}]
ver1   来自deepin的patch版本,这块必须，且从0开始
ver2   安全补丁版本，这块只有发布安全补丁时需要
ver3   CI编译版本，这快只有CI编译时有
ver3   rebuild次数，这块只有rebuild时才添加

2024-08-19 08:15 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
针对不用情况下使用不同的版本号规范，上述的很多情况都是少数情况下才会使用，开发者&审阅者需要判断当前软件包处理什么状态
其次这个规范本就是全局统一的, 只是分不同的情况分开讨论了

2024-08-19 08:15 UTC, BLumia approved these changes

2024-08-19 08:16 UTC, UTsweetyfish commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
> 为啥不定一个全局统一的版本号规范呢，这样的话不用判断那么多种情况了 我的建议如下 upstreamversion+deepin${ver1}[+dp26u${ver2}][+u${ver3}][+rb${ver4}] ver1 来自deepin的patch版本,这块必须，且从0开始 ver2 安全补丁版本，这块只有发布安全补丁时需要 ver3 CI编译版本，这快只有CI编译时有 ver4 rebuild次数，这块只有rebuild时才添加



因为我们要定主线/非主线
主线是没有安全补丁、CI编译的，只有rebuild

2024-08-19 08:57 UTC, kt286 commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
> > 为啥不定一个全局统一的版本号规范呢，这样的话不用判断那么多种情况了 我的建议如下 upstreamversion+deepin${ver1}[+dp26u${ver2}][+u${ver3}][+rb${ver4}] ver1 来自deepin的patch版本,这块必须，且从0开始 ver2 安全补丁版本，这块只有发布安全补丁时需要 ver3 CI编译版本，这快只有CI编译时有 ver4 rebuild次数，这块只有rebuild时才添加
> 
> 因为我们要定主线/非主线 主线是没有安全补丁、CI编译的，只有rebuild

我这个是所有的都使用同一个格式, upstreamversion 后跟了四大块，[] 里的内容是非必须的，需要的时候添加，这样可以组合出文章里提到的全部情况
`upstreamversion` `+deepin${ver1}` `[+dp26u${ver2}]` `[+u${ver3}]` `[+rb${ver4}]`

2024-08-19 09:10 UTC, UTsweetyfish commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
> > 针对不用情况下使用不同的版本号规范，上述的很多情况都是少数情况下才会使用，开发者&审阅者需要判断当前软件包处理什么状态 其次这个规范本就是全局统一的, 只是分不同的情况分开讨论了
> 
> 我的意思是不同情况下格式不太一样，我上边的建议是统一的格式，需要的项目自由增删 `upstreamversion` `+deepin${ver1}` `[+dp26u${ver2}]` `[+u${ver3}]` `[+rb${ver4}]`

其实可能应该明确在rfc里这么写：
1. 主线 GitHub 版本为 `${UPVER}-${VER1}deepin${VER2}`；
2. 主线仓库会有 `[+rb]`，不在 GitHub，在 OBS 生成；
3. 安全更新在 GitHub，非主线，有 `[+dp26u]；
4. [+u] 为开发版本，在GitHub内不出现，在仓库内不出现，但是出现在 CI 中。

2024-08-19 09:19 UTC, UTsweetyfish commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
写了个 BNF
```
<VER_UPSTREAM> ::= "1.0.0"
<VER_EPOCH> ::= "1:"
<VER_DEBIAN> ::= "1"
<VER_DEEPIN> ::= "0deepin1" | <VER_DEBIAN> "deepin1"
<REBUILD_COUNT> ::= "1"

<VER_MAINLINE_GITHUB> ::= [<VER_EPOCH>] <VER_UPSTREAM> "-" (<VER_DEBIAN> | <VER_DEEPIN>)
<VER_MAINLINE_REPO> ::= [<VER_EPOCH>] <VER_UPSTREAM> "-" <VER_DEEPIN> "+rb" <REBUILD_COUNT>
<VER_SECURITY_GITHUB> ::= <VER_MAINLINE_GITHUB> "+dp26u1"
<VER_SECURITY_REPO> ::= <VER_SECURITY_GITHUB> ["+rb1"]
<VER_CI> ::= <VER_MAINLINE_GITHUB> "+u001"
```
可以看一下有没有问题

2024-08-19 10:07 UTC, UTsweetyfish commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
> 可以看一下有没有问题

写完 BNF 之后意识到问题了

假设当前主线版本为 `1.0.0-1deepin1`，仓库版本为 `1.0.0-1deepin1+rb1`，由于 `+dp23u1` 是小于 `+rb1` 的，但是安全更新不是主线，这个时候安全团队该如何升级？

1. `1.0.0-1deepin1+rb1+dp23u1`: 在 `+rb1` 后加 `+dp23u1`，可能不太好
2. `1.0.0-1deepin1.1`: 类似 nmu 的形式，但是没有 `+dp23u1`
3. `1.0.0-1deepin1.1+dp23u1`: 类似 nmu 的形式，此时 `+dp23u1`  仅作标识
4. `1.0.0-1deepin2~dp23u1`: 类似 backport 的形式
5. `1.0.0-1deepin2`: bump ver2

2024-08-19 10:11 UTC, RevySR commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
1.0.0-1deepin1+rb1+dp23u1: 在 +rb1 后加 +dp23u1，可能不太好

> 1.0.0-1deepin1dp23u1 呢

2024-08-19 10:23 UTC, UTsweetyfish requested changes
hold due to https://github.com/deepin-community/rfcs/pull/12/files#r1721540877

2024-08-19 10:23 UTC, UTsweetyfish commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
> > 1.0.0-1deepin1+rb1+dp23u1: 在 +rb1 后加 +dp23u1，可能不太好
> 
> 1.0.0-1deepin1dp23u1 呢

不行，会降级

```shell
$ dpkg --compare-versions 1.0.0-1deepin1+rb1 lt 1.0.0-1deepin1dp23u1
$ echo $?
1
```

2024-08-20 00:18 UTC, kt286 commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
+dp23u1 改成 +s23u1 呢？

2024-08-20 01:37 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
> +dp23u1 改成 +s23u1 呢？

这个s又指代什么呢 有点不明所以

2024-08-20 02:38 UTC, kt286 commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
> > +dp23u1 改成 +s23u1 呢？
> 
> 这个s又指代什么呢 有点不明所以

不是安全更新么 security

2024-08-21 02:50 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
使用 [UTsweetyfish](https://github.com/UTsweetyfish) 提的方案3 也就不需要改这个了

2024-08-21 06:28 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
@kt286 @RevySR  @UTsweetyfish 已更新 用UTsweetyfish提出的方案三解决 +dp23u1 < rb1 的问题 ，请各位及时review或提出其他问题

2024-08-21 08:29 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
BNF已经加入正文中

2024-08-21 09:04 UTC, UTsweetyfish approved these changes
lgtm now. 需注意:
1. BNF 中的部分规则（如 `UPSTREAM_VERSION`、`DEBIAN_REVISION`）仅为示例，如部署相关检查时应以实际情况为主。
2. `VER_DEEPIN_MAJOR` 目前只规定了 23 与 25，也应以实际为主。
3. CI 版本不应有 REBUILD_TAG。

2024-08-22 02:18 UTC, Zeno-sole commented on rfcs/0012-changelog-specification.md
> +`upstreamversion-${ver1}deepin${ver2}`
@kt286 @RevySR  @UTsweetyfish   BNF已更新 请及时review  期望本周内能merge

2024-08-22 03:34 UTC, shiptux commented
/approve

2024-08-23 07:38 UTC, Zeno-sole commented
该提案已经进入最终的评审流程，如无其他意见本提案将于2024-08-19日合并 各位悉知

2024-08-23 07:39 UTC, UTsweetyfish commented
> 该提案已经进入最终的评审流程，如无其他意见本提案将于2024-08-19日合并 各位悉知

今天已经是 20240823 了

2024-08-26 05:40 UTC, Zeno-sole commented
/approve

2024-08-26 05:41 UTC, merged