rfcs - 增加龙架构支持
deepin-community/rfcs pull request #2
Opened 2023-05-05 19:59 UTC by Rabenda

2023-05-06 01:34 UTC, BLumia reviewed
copywriting corrections

2023-05-06 01:34 UTC, BLumia commented on rfcs/0002-增加龙架构支持.md
> +- 试做的软件版本大部分都高于 Deepin 主线 后续会有合并工作
```suggestion
- 试做的软件版本大部分都高于 deepin 主线，后续会有合并工作
```

2023-05-06 01:34 UTC, BLumia commented on rfcs/0002-增加龙架构支持.md
> +- 部分软件还没有主线合并完成，比如rust还有一些支持不够完善，有一定工作量
```suggestion
- 部分软件还没有主线合并完成，比如 Rust 还有一些支持不够完善，有一定工作量
```

2023-05-06 01:34 UTC, BLumia commented on rfcs/0002-增加龙架构支持.md
> +提案人对 Deepin 龙架构试做 已经完成3000+软件包，可以完成基本启动与构建
```suggestion
提案人对 deepin 龙架构试做已经完成 3000+ 软件包，可以完成基本启动与构建
```

根据 deepin 品牌名称使用规范，单独使用 deepin 表示深度品牌时，首字母 d 应保持小写。

2023-05-06 01:34 UTC, BLumia commented on rfcs/0002-增加龙架构支持.md
> +龙芯架构 LoongArch 是一种精简指令集计算机（Reduced Instruction Set Computing，简称 RISC）风格的指令系统架构。
```suggestion
龙架构（LoongArch，也被称为龙芯架构）是一种精简指令集计算机（Reduced Instruction Set Computing，简称 RISC）风格的指令系统架构。
```

下方使用的术语均为“龙架构”，定义的时候也建议使用相同的名称，并将“龙芯架构”作为额外的补充说明。

2023-05-06 01:37 UTC, zccrs requested changes
Deepin 应该为 deepin，具体参见：https://wiki.deepin.org/zh/03_%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83/01_%E6%96%87%E6%A1%A3%E8%A7%84%E8%8C%83/%E5%93%81%E7%89%8C%E4%B8%93%E6%9C%89%E5%90%8D%E8%AF%8D%E6%8C%87%E5%AF%BC%E6%96%B9%E9%92%88

2023-05-06 03:23 UTC, Rabenda commented on rfcs/0002-增加龙架构支持.md
> +龙芯架构 LoongArch 是一种精简指令集计算机（Reduced Instruction Set Computing，简称 RISC）风格的指令系统架构。
本段摘自指令集手册卷一 所以不会修改

2023-05-06 04:05 UTC, BLumia commented on rfcs/0002-增加龙架构支持.md
> +龙芯架构 LoongArch 是一种精简指令集计算机（Reduced Instruction Set Computing，简称 RISC）风格的指令系统架构。
是否应当考虑补充说明？并不是要求必须按我给出的这么改，但全文只有这里在使用“龙芯架构”的描述，且从未定义剩余位置所使用的“龙架构”一词，怎么看都怪怪的。

2023-05-06 04:45 UTC, Rabenda commented on rfcs/0002-增加龙架构支持.md
> +龙芯架构 LoongArch 是一种精简指令集计算机（Reduced Instruction Set Computing，简称 RISC）风格的指令系统架构。
这个叙述是历史原因 龙架构/龙芯架构基本都是等效词语 前者现在用的人比较多了

2023-05-06 05:59 UTC, BLumia commented on rfcs/0002-增加龙架构支持.md
> +龙芯架构 LoongArch 是一种精简指令集计算机（Reduced Instruction Set Computing，简称 RISC）风格的指令系统架构。
既然“龙芯架构”是历史叫法，现在使用的人也不多了，是否应当提议更新《指令集手册卷一》中的描述为“龙架构”？

2023-05-06 16:27 UTC, Rabenda commented on rfcs/0002-增加龙架构支持.md
> +龙芯架构 LoongArch 是一种精简指令集计算机（Reduced Instruction Set Computing，简称 RISC）风格的指令系统架构。
> 既然“龙芯架构”是历史叫法，现在使用的人也不多了，是否应当提议更新《指令集手册卷一》中的描述为“龙架构”？

龙芯主动关闭了指令集手册的反馈渠道 现阶段似乎也不接受任何提议

2023-05-22 01:52 UTC, Zeno-sole commented
@hudeng-go  add review

2023-07-26 12:49 UTC, closed without merging

2023-08-02 09:02 UTC, hudeng-go commented
目前已经使用有限的龙架构硬件资源基于obs搭建了基础的loong64构建环境，并且通过[deepin-ports](https://build.deepin.com/project/show/home:yukarichiba:deepin-ports)项目在进行批量构建